
version: '3.8'

services:
  postgres:
    image: postgres:9-alpine
    restart: always
    environment:
      POSTGRES_DB: alvaro
      POSTGRES_USER: root
      POSTGRES_PASSWORD: clave1
    volumes:
      - $HOME/datos-postgressql:/var/lib/postgresql/data:rw
      - ./Productos.sql:/docker-entrypoint-initdb.d/Productos.sql:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - 9091:8080
    depends_on:
      - postgres

  apache:
    build: ./apache
    ports:
      - 9092:80
    restart: unless-stopped
    depends_on:
      - php
      - postgres
    environment:
      FLUENTD_HOST: "fluentd"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: "true"
        tag: apache.access

  php:
    build: ./php
    container_name: php
    working_dir: /var/www/html
    restart: unless-stopped
    environment:
      BBDD_CADENA_CONEXION: "pgsql:host=postgres;port=5432;dbname=alvaro"
      BBDD_USUARIO: root
      BBDD_CLAVE: clave1
    expose:
      - 80

  fluentd:
    image: registry.cn-shenzhen.aliyuncs.com/cnregistry/fluentd-es:v1.16.2-debian-1.1
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    ports:
      - 9200:9200
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
